title: "My Portfolio"
description: "Welcome to my professional portfolio"
theme: jekyll-theme-cayman

# Social links
linkedin: https://www.linkedin.com/in/samiha-z/
github: https://github.com/samihazaman
